name: ganzhi
description: A new Flutter project.
version: 0.0.3+3

environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lunar: ^1.6.1
  provider: ^6.0.5
  selector_wheel: ^1.1.2
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: ZS
  #     fonts:
  #       - asset: assets/zs.ttf
